;;;; package.lisp
;;;; Auto-generated CFFI bindings for Dear ImGui
;;;; Generated from dcimgui.json

(defpackage #:cl-dear-imgui
  (:use #:cl #:cffi)
  (:export
   #:+font-atlas-rect-id-invalid+
   #:+im-col32-a-mask+
   #:+im-col32-a-shift+
   #:+im-col32-b-shift+
   #:+im-col32-g-shift+
   #:+im-col32-r-shift+
   #:+im-drawlist-tex-lines-width-max+
   #:+im-unicode-codepoint-invalid+
   #:+im-unicode-codepoint-max+
   #:+payload-type-color-3f+
   #:+payload-type-color-4f+
   #:+version+
   #:+version-num+
   #:--anonymous-type0
   #:--anonymous-type1
   #:accept-drag-drop-payload
   #:align-text-to-frame-padding
   #:arrow-button
   #:backend-flags
   #:backend-flags-has-gamepad
   #:backend-flags-has-mouse-cursors
   #:backend-flags-has-set-mouse-pos
   #:backend-flags-none
   #:backend-flags-renderer-has-textures
   #:backend-flags-renderer-has-vtx-offset
   #:begin
   #:begin-child
   #:begin-child-frame
   #:begin-child-frame-ex
   #:begin-child-id
   #:begin-combo
   #:begin-disabled
   #:begin-drag-drop-source
   #:begin-drag-drop-target
   #:begin-group
   #:begin-item-tooltip
   #:begin-list-box
   #:begin-main-menu-bar
   #:begin-menu
   #:begin-menu-bar
   #:begin-menu-ex
   #:begin-multi-select
   #:begin-multi-select-ex
   #:begin-popup
   #:begin-popup-context-item
   #:begin-popup-context-item-ex
   #:begin-popup-context-void
   #:begin-popup-context-void-ex
   #:begin-popup-context-window
   #:begin-popup-context-window-ex
   #:begin-popup-modal
   #:begin-tab-bar
   #:begin-tab-item
   #:begin-table
   #:begin-table-ex
   #:begin-tooltip
   #:bullet
   #:bullet-text
   #:bullet-text-v
   #:button
   #:button-ex
   #:button-flags
   #:button-flags-enable-nav
   #:button-flags-mouse-button-left
   #:button-flags-mouse-button-mask-
   #:button-flags-mouse-button-middle
   #:button-flags-mouse-button-right
   #:button-flags-none
   #:calc-item-width
   #:calc-text-size
   #:calc-text-size-ex
   #:checkbox
   #:checkbox-flags-int-ptr
   #:checkbox-flags-uint-ptr
   #:child-flags
   #:child-flags-always-auto-resize
   #:child-flags-always-use-window-padding
   #:child-flags-auto-resize-x
   #:child-flags-auto-resize-y
   #:child-flags-borders
   #:child-flags-frame-style
   #:child-flags-nav-flattened
   #:child-flags-none
   #:child-flags-resize-x
   #:child-flags-resize-y
   #:close-current-popup
   #:col
   #:col-border
   #:col-border-shadow
   #:col-button
   #:col-button-active
   #:col-button-hovered
   #:col-check-mark
   #:col-child-bg
   #:col-count
   #:col-drag-drop-target
   #:col-drag-drop-target-bg
   #:col-frame-bg
   #:col-frame-bg-active
   #:col-frame-bg-hovered
   #:col-header
   #:col-header-active
   #:col-header-hovered
   #:col-input-text-cursor
   #:col-menu-bar-bg
   #:col-modal-window-dim-bg
   #:col-nav-cursor
   #:col-nav-highlight
   #:col-nav-windowing-dim-bg
   #:col-nav-windowing-highlight
   #:col-plot-histogram
   #:col-plot-histogram-hovered
   #:col-plot-lines
   #:col-plot-lines-hovered
   #:col-popup-bg
   #:col-resize-grip
   #:col-resize-grip-active
   #:col-resize-grip-hovered
   #:col-scrollbar-bg
   #:col-scrollbar-grab
   #:col-scrollbar-grab-active
   #:col-scrollbar-grab-hovered
   #:col-separator
   #:col-separator-active
   #:col-separator-hovered
   #:col-slider-grab
   #:col-slider-grab-active
   #:col-tab
   #:col-tab-active
   #:col-tab-dimmed
   #:col-tab-dimmed-selected
   #:col-tab-dimmed-selected-overline
   #:col-tab-hovered
   #:col-tab-selected
   #:col-tab-selected-overline
   #:col-tab-unfocused
   #:col-tab-unfocused-active
   #:col-table-border-light
   #:col-table-border-strong
   #:col-table-header-bg
   #:col-table-row-bg
   #:col-table-row-bg-alt
   #:col-text
   #:col-text-disabled
   #:col-text-link
   #:col-text-selected-bg
   #:col-title-bg
   #:col-title-bg-active
   #:col-title-bg-collapsed
   #:col-tree-lines
   #:col-unsaved-marker
   #:col-window-bg
   #:collapsing-header
   #:collapsing-header-bool-ptr
   #:color
   #:color-button
   #:color-button-ex
   #:color-convert-float4to-u32
   #:color-convert-hsvto-rgb
   #:color-convert-rgbto-hsv
   #:color-convert-u32to-float4
   #:color-edit-flags
   #:color-edit-flags-alpha-bar
   #:color-edit-flags-alpha-mask-
   #:color-edit-flags-alpha-no-bg
   #:color-edit-flags-alpha-opaque
   #:color-edit-flags-alpha-preview
   #:color-edit-flags-alpha-preview-half
   #:color-edit-flags-data-type-mask-
   #:color-edit-flags-default-options-
   #:color-edit-flags-display-hex
   #:color-edit-flags-display-hsv
   #:color-edit-flags-display-mask-
   #:color-edit-flags-display-rgb
   #:color-edit-flags-float
   #:color-edit-flags-hdr
   #:color-edit-flags-input-hsv
   #:color-edit-flags-input-mask-
   #:color-edit-flags-input-rgb
   #:color-edit-flags-no-alpha
   #:color-edit-flags-no-border
   #:color-edit-flags-no-color-markers
   #:color-edit-flags-no-drag-drop
   #:color-edit-flags-no-inputs
   #:color-edit-flags-no-label
   #:color-edit-flags-no-options
   #:color-edit-flags-no-picker
   #:color-edit-flags-no-side-preview
   #:color-edit-flags-no-small-preview
   #:color-edit-flags-no-tooltip
   #:color-edit-flags-none
   #:color-edit-flags-picker-hue-bar
   #:color-edit-flags-picker-hue-wheel
   #:color-edit-flags-picker-mask-
   #:color-edit-flags-uint8
   #:color-edit3
   #:color-edit4
   #:color-hsv
   #:color-picker3
   #:color-picker4
   #:color-set-hsv
   #:columns
   #:columns-ex
   #:combo
   #:combo-callback
   #:combo-callback-ex
   #:combo-char
   #:combo-char-ex
   #:combo-ex
   #:combo-flags
   #:combo-flags-height-large
   #:combo-flags-height-largest
   #:combo-flags-height-mask-
   #:combo-flags-height-regular
   #:combo-flags-height-small
   #:combo-flags-no-arrow-button
   #:combo-flags-no-preview
   #:combo-flags-none
   #:combo-flags-popup-align-left
   #:combo-flags-width-fit-preview
   #:combo-obsolete
   #:combo-obsolete-ex
   #:cond
   #:cond-always
   #:cond-appearing
   #:cond-first-use-ever
   #:cond-none
   #:cond-once
   #:config-flags
   #:config-flags-is-srgb
   #:config-flags-is-touch-screen
   #:config-flags-nav-enable-gamepad
   #:config-flags-nav-enable-keyboard
   #:config-flags-nav-enable-set-mouse-pos
   #:config-flags-nav-no-capture-keyboard
   #:config-flags-no-keyboard
   #:config-flags-no-mouse
   #:config-flags-no-mouse-cursor-change
   #:config-flags-none
   #:create-context
   #:data-type
   #:data-type-bool
   #:data-type-count
   #:data-type-double
   #:data-type-float
   #:data-type-s16
   #:data-type-s32
   #:data-type-s64
   #:data-type-s8
   #:data-type-string
   #:data-type-u16
   #:data-type-u32
   #:data-type-u64
   #:data-type-u8
   #:debug-check-version-and-data-layout
   #:debug-flash-style-color
   #:debug-log
   #:debug-log-v
   #:debug-start-item-picker
   #:debug-text-encoding
   #:destroy-context
   #:dir
   #:dir-count
   #:dir-down
   #:dir-left
   #:dir-none
   #:dir-right
   #:dir-up
   #:drag-drop-flags
   #:drag-drop-flags-accept-before-delivery
   #:drag-drop-flags-accept-draw-as-hovered
   #:drag-drop-flags-accept-no-draw-default-rect
   #:drag-drop-flags-accept-no-preview-tooltip
   #:drag-drop-flags-accept-peek-only
   #:drag-drop-flags-none
   #:drag-drop-flags-payload-auto-expire
   #:drag-drop-flags-payload-no-cross-context
   #:drag-drop-flags-payload-no-cross-process
   #:drag-drop-flags-source-allow-null-id
   #:drag-drop-flags-source-auto-expire-payload
   #:drag-drop-flags-source-extern
   #:drag-drop-flags-source-no-disable-hover
   #:drag-drop-flags-source-no-hold-to-open-others
   #:drag-drop-flags-source-no-preview-tooltip
   #:drag-float
   #:drag-float-ex
   #:drag-float-range2
   #:drag-float-range2ex
   #:drag-float2
   #:drag-float2ex
   #:drag-float3
   #:drag-float3ex
   #:drag-float4
   #:drag-float4ex
   #:drag-int
   #:drag-int-ex
   #:drag-int-range2
   #:drag-int-range2ex
   #:drag-int2
   #:drag-int2ex
   #:drag-int3
   #:drag-int3ex
   #:drag-int4
   #:drag-int4ex
   #:drag-scalar
   #:drag-scalar-ex
   #:drag-scalar-n
   #:drag-scalar-nex
   #:draw-callback
   #:draw-channel
   #:draw-cmd
   #:draw-cmd-get-tex-id
   #:draw-cmd-header
   #:draw-data
   #:draw-data-add-draw-list
   #:draw-data-clear
   #:draw-data-de-index-all-buffers
   #:draw-data-scale-clip-rects
   #:draw-flags
   #:draw-flags-closed
   #:draw-flags-none
   #:draw-flags-round-corners-all
   #:draw-flags-round-corners-bottom
   #:draw-flags-round-corners-bottom-left
   #:draw-flags-round-corners-bottom-right
   #:draw-flags-round-corners-default-
   #:draw-flags-round-corners-left
   #:draw-flags-round-corners-mask-
   #:draw-flags-round-corners-none
   #:draw-flags-round-corners-right
   #:draw-flags-round-corners-top
   #:draw-flags-round-corners-top-left
   #:draw-flags-round-corners-top-right
   #:draw-idx
   #:draw-list
   #:draw-list--calc-circle-auto-segment-count
   #:draw-list--clear-free-memory
   #:draw-list--on-changed-clip-rect
   #:draw-list--on-changed-texture
   #:draw-list--on-changed-vtx-offset
   #:draw-list--path-arc-to-fast-ex
   #:draw-list--path-arc-to-n
   #:draw-list--pop-unused-draw-cmd
   #:draw-list--reset-for-new-frame
   #:draw-list--set-draw-list-shared-data
   #:draw-list--set-texture
   #:draw-list--try-merge-draw-cmds
   #:draw-list-add-bezier-cubic
   #:draw-list-add-bezier-quadratic
   #:draw-list-add-callback
   #:draw-list-add-callback-ex
   #:draw-list-add-circle
   #:draw-list-add-circle-ex
   #:draw-list-add-circle-filled
   #:draw-list-add-concave-poly-filled
   #:draw-list-add-convex-poly-filled
   #:draw-list-add-draw-cmd
   #:draw-list-add-ellipse
   #:draw-list-add-ellipse-ex
   #:draw-list-add-ellipse-filled
   #:draw-list-add-ellipse-filled-ex
   #:draw-list-add-image
   #:draw-list-add-image-ex
   #:draw-list-add-image-quad
   #:draw-list-add-image-quad-ex
   #:draw-list-add-image-rounded
   #:draw-list-add-line
   #:draw-list-add-line-ex
   #:draw-list-add-ngon
   #:draw-list-add-ngon-ex
   #:draw-list-add-ngon-filled
   #:draw-list-add-polyline
   #:draw-list-add-quad
   #:draw-list-add-quad-ex
   #:draw-list-add-quad-filled
   #:draw-list-add-rect
   #:draw-list-add-rect-ex
   #:draw-list-add-rect-filled
   #:draw-list-add-rect-filled-ex
   #:draw-list-add-rect-filled-multi-color
   #:draw-list-add-text
   #:draw-list-add-text-ex
   #:draw-list-add-text-im-font-ptr
   #:draw-list-add-text-im-font-ptr-ex
   #:draw-list-add-triangle
   #:draw-list-add-triangle-ex
   #:draw-list-add-triangle-filled
   #:draw-list-channels-merge
   #:draw-list-channels-set-current
   #:draw-list-channels-split
   #:draw-list-clone-output
   #:draw-list-flags
   #:draw-list-flags-allow-vtx-offset
   #:draw-list-flags-anti-aliased-fill
   #:draw-list-flags-anti-aliased-lines
   #:draw-list-flags-anti-aliased-lines-use-tex
   #:draw-list-flags-none
   #:draw-list-get-clip-rect-max
   #:draw-list-get-clip-rect-min
   #:draw-list-path-arc-to
   #:draw-list-path-arc-to-fast
   #:draw-list-path-bezier-cubic-curve-to
   #:draw-list-path-bezier-quadratic-curve-to
   #:draw-list-path-clear
   #:draw-list-path-elliptical-arc-to
   #:draw-list-path-elliptical-arc-to-ex
   #:draw-list-path-fill-concave
   #:draw-list-path-fill-convex
   #:draw-list-path-line-to
   #:draw-list-path-line-to-merge-duplicate
   #:draw-list-path-rect
   #:draw-list-path-stroke
   #:draw-list-pop-clip-rect
   #:draw-list-pop-texture
   #:draw-list-pop-texture-id
   #:draw-list-prim-quad-uv
   #:draw-list-prim-rect
   #:draw-list-prim-rect-uv
   #:draw-list-prim-reserve
   #:draw-list-prim-unreserve
   #:draw-list-prim-vtx
   #:draw-list-prim-write-idx
   #:draw-list-prim-write-vtx
   #:draw-list-push-clip-rect
   #:draw-list-push-clip-rect-full-screen
   #:draw-list-push-texture
   #:draw-list-push-texture-id
   #:draw-list-splitter
   #:draw-list-splitter-clear
   #:draw-list-splitter-clear-free-memory
   #:draw-list-splitter-merge
   #:draw-list-splitter-set-current-channel
   #:draw-list-splitter-split
   #:draw-text-flags
   #:draw-vert
   #:dummy
   #:end
   #:end-child
   #:end-child-frame
   #:end-combo
   #:end-disabled
   #:end-drag-drop-source
   #:end-drag-drop-target
   #:end-frame
   #:end-group
   #:end-list-box
   #:end-main-menu-bar
   #:end-menu
   #:end-menu-bar
   #:end-multi-select
   #:end-popup
   #:end-tab-bar
   #:end-tab-item
   #:end-table
   #:end-tooltip
   #:focused-flags
   #:focused-flags-any-window
   #:focused-flags-child-windows
   #:focused-flags-no-popup-hierarchy
   #:focused-flags-none
   #:focused-flags-root-and-child-windows
   #:focused-flags-root-window
   #:font
   #:font-add-remap-char
   #:font-atlas
   #:font-atlas-add-custom-rect
   #:font-atlas-add-custom-rect-font-glyph
   #:font-atlas-add-custom-rect-font-glyph-for-size
   #:font-atlas-add-custom-rect-regular
   #:font-atlas-add-font
   #:font-atlas-add-font-default
   #:font-atlas-add-font-from-file-ttf
   #:font-atlas-add-font-from-memory-compressed-base85ttf
   #:font-atlas-add-font-from-memory-compressed-ttf
   #:font-atlas-add-font-from-memory-ttf
   #:font-atlas-build
   #:font-atlas-calc-custom-rect-uv
   #:font-atlas-clear
   #:font-atlas-clear-fonts
   #:font-atlas-clear-input-data
   #:font-atlas-clear-tex-data
   #:font-atlas-compact-cache
   #:font-atlas-custom-rect
   #:font-atlas-flags
   #:font-atlas-flags-no-baked-lines
   #:font-atlas-flags-no-mouse-cursors
   #:font-atlas-flags-no-power-of-two-height
   #:font-atlas-flags-none
   #:font-atlas-get-custom-rect
   #:font-atlas-get-custom-rect-by-index
   #:font-atlas-get-glyph-ranges-chinese-full
   #:font-atlas-get-glyph-ranges-chinese-simplified-common
   #:font-atlas-get-glyph-ranges-cyrillic
   #:font-atlas-get-glyph-ranges-default
   #:font-atlas-get-glyph-ranges-greek
   #:font-atlas-get-glyph-ranges-japanese
   #:font-atlas-get-glyph-ranges-korean
   #:font-atlas-get-glyph-ranges-thai
   #:font-atlas-get-glyph-ranges-vietnamese
   #:font-atlas-get-tex-data-as-alpha8
   #:font-atlas-get-tex-data-as-rgba32
   #:font-atlas-is-built
   #:font-atlas-rect
   #:font-atlas-rect-id
   #:font-atlas-remove-custom-rect
   #:font-atlas-remove-font
   #:font-atlas-set-font-loader
   #:font-atlas-set-tex-id
   #:font-atlas-set-tex-idim-texture-ref
   #:font-baked
   #:font-baked-clear-output-data
   #:font-baked-find-glyph
   #:font-baked-find-glyph-no-fallback
   #:font-baked-get-char-advance
   #:font-baked-is-glyph-loaded
   #:font-calc-text-size-a
   #:font-calc-text-size-aex
   #:font-calc-word-wrap-position
   #:font-calc-word-wrap-position-a
   #:font-clear-output-data
   #:font-config
   #:font-flags
   #:font-flags-lock-baked-sizes
   #:font-flags-no-load-error
   #:font-flags-no-load-glyphs
   #:font-flags-none
   #:font-get-debug-name
   #:font-get-font-baked
   #:font-get-font-baked-ex
   #:font-glyph
   #:font-glyph-ranges-builder
   #:font-glyph-ranges-builder-add-char
   #:font-glyph-ranges-builder-add-ranges
   #:font-glyph-ranges-builder-add-text
   #:font-glyph-ranges-builder-build-ranges
   #:font-glyph-ranges-builder-clear
   #:font-glyph-ranges-builder-get-bit
   #:font-glyph-ranges-builder-set-bit
   #:font-is-glyph-in-font
   #:font-is-glyph-range-unused
   #:font-is-loaded
   #:font-render-char
   #:font-render-char-ex
   #:font-render-text
   #:get-allocator-functions
   #:get-background-draw-list
   #:get-clipboard-text
   #:get-color-u32
   #:get-color-u32ex
   #:get-color-u32im-u32
   #:get-color-u32im-u32ex
   #:get-color-u32im-vec4
   #:get-column-index
   #:get-column-offset
   #:get-column-width
   #:get-columns-count
   #:get-content-region-avail
   #:get-content-region-max
   #:get-current-context
   #:get-cursor-pos
   #:get-cursor-pos-x
   #:get-cursor-pos-y
   #:get-cursor-screen-pos
   #:get-cursor-start-pos
   #:get-drag-drop-payload
   #:get-draw-data
   #:get-draw-list-shared-data
   #:get-font
   #:get-font-baked
   #:get-font-size
   #:get-font-tex-uv-white-pixel
   #:get-foreground-draw-list
   #:get-frame-count
   #:get-frame-height
   #:get-frame-height-with-spacing
   #:get-id
   #:get-idint
   #:get-idptr
   #:get-idstr
   #:get-io
   #:get-item-id
   #:get-item-rect-max
   #:get-item-rect-min
   #:get-item-rect-size
   #:get-key-name
   #:get-key-pressed-amount
   #:get-main-viewport
   #:get-mouse-clicked-count
   #:get-mouse-cursor
   #:get-mouse-drag-delta
   #:get-mouse-pos
   #:get-mouse-pos-on-opening-current-popup
   #:get-platform-io
   #:get-scroll-max-x
   #:get-scroll-max-y
   #:get-scroll-x
   #:get-scroll-y
   #:get-state-storage
   #:get-style
   #:get-style-color-name
   #:get-style-color-vec4
   #:get-text-line-height
   #:get-text-line-height-with-spacing
   #:get-time
   #:get-tree-node-to-label-spacing
   #:get-version
   #:get-window-content-region-max
   #:get-window-content-region-min
   #:get-window-draw-list
   #:get-window-height
   #:get-window-pos
   #:get-window-size
   #:get-window-width
   #:hovered-flags
   #:hovered-flags-allow-when-blocked-by-active-item
   #:hovered-flags-allow-when-blocked-by-popup
   #:hovered-flags-allow-when-disabled
   #:hovered-flags-allow-when-overlapped
   #:hovered-flags-allow-when-overlapped-by-item
   #:hovered-flags-allow-when-overlapped-by-window
   #:hovered-flags-any-window
   #:hovered-flags-child-windows
   #:hovered-flags-delay-none
   #:hovered-flags-delay-normal
   #:hovered-flags-delay-short
   #:hovered-flags-for-tooltip
   #:hovered-flags-no-nav-override
   #:hovered-flags-no-popup-hierarchy
   #:hovered-flags-no-shared-delay
   #:hovered-flags-none
   #:hovered-flags-rect-only
   #:hovered-flags-root-and-child-windows
   #:hovered-flags-root-window
   #:hovered-flags-stationary
   #:id
   #:im-backend-flags
   #:im-button-flags
   #:im-child-flags
   #:im-col
   #:im-color-edit-flags
   #:im-combo-flags
   #:im-cond
   #:im-config-flags
   #:im-data-type
   #:im-dir
   #:im-drag-drop-flags
   #:im-draw-flags
   #:im-draw-list-flags
   #:im-focused-flags
   #:im-font-atlas-flags
   #:im-font-flags
   #:im-hovered-flags
   #:im-input-flags
   #:im-input-text-flags
   #:im-item-flags
   #:im-key
   #:im-list-clipper-flags
   #:im-mouse-button
   #:im-mouse-cursor
   #:im-mouse-source
   #:im-multi-select-flags
   #:im-popup-flags
   #:im-selectable-flags
   #:im-selection-request-type
   #:im-slider-flags
   #:im-sort-direction
   #:im-style-var
   #:im-tab-bar-flags
   #:im-tab-item-flags
   #:im-table-bg-target
   #:im-table-column-flags
   #:im-table-flags
   #:im-table-row-flags
   #:im-texture-format
   #:im-texture-status
   #:im-tree-node-flags
   #:im-viewport-flags
   #:im-window-flags
   #:image
   #:image-button
   #:image-button-ex
   #:image-ex
   #:image-im-vec4
   #:image-with-bg
   #:image-with-bg-ex
   #:indent
   #:indent-ex
   #:input-double
   #:input-double-ex
   #:input-flags
   #:input-flags-none
   #:input-flags-repeat
   #:input-flags-route-active
   #:input-flags-route-always
   #:input-flags-route-focused
   #:input-flags-route-from-root-window
   #:input-flags-route-global
   #:input-flags-route-over-active
   #:input-flags-route-over-focused
   #:input-flags-route-unless-bg-focused
   #:input-flags-tooltip
   #:input-float
   #:input-float-ex
   #:input-float2
   #:input-float2ex
   #:input-float3
   #:input-float3ex
   #:input-float4
   #:input-float4ex
   #:input-int
   #:input-int-ex
   #:input-int2
   #:input-int3
   #:input-int4
   #:input-scalar
   #:input-scalar-ex
   #:input-scalar-n
   #:input-scalar-nex
   #:input-text
   #:input-text-callback
   #:input-text-callback-data
   #:input-text-callback-data-clear-selection
   #:input-text-callback-data-delete-chars
   #:input-text-callback-data-has-selection
   #:input-text-callback-data-insert-chars
   #:input-text-callback-data-select-all
   #:input-text-ex
   #:input-text-flags
   #:input-text-flags-allow-tab-input
   #:input-text-flags-always-overwrite
   #:input-text-flags-auto-select-all
   #:input-text-flags-callback-always
   #:input-text-flags-callback-char-filter
   #:input-text-flags-callback-completion
   #:input-text-flags-callback-edit
   #:input-text-flags-callback-history
   #:input-text-flags-callback-resize
   #:input-text-flags-chars-decimal
   #:input-text-flags-chars-hexadecimal
   #:input-text-flags-chars-no-blank
   #:input-text-flags-chars-scientific
   #:input-text-flags-chars-uppercase
   #:input-text-flags-ctrl-enter-for-new-line
   #:input-text-flags-display-empty-ref-val
   #:input-text-flags-elide-left
   #:input-text-flags-enter-returns-true
   #:input-text-flags-escape-clears-all
   #:input-text-flags-no-horizontal-scroll
   #:input-text-flags-no-undo-redo
   #:input-text-flags-none
   #:input-text-flags-parse-empty-ref-val
   #:input-text-flags-password
   #:input-text-flags-read-only
   #:input-text-flags-word-wrap
   #:input-text-multiline
   #:input-text-multiline-ex
   #:input-text-with-hint
   #:input-text-with-hint-ex
   #:invisible-button
   #:io
   #:io-add-focus-event
   #:io-add-input-character
   #:io-add-input-character-utf16
   #:io-add-input-characters-utf8
   #:io-add-key-analog-event
   #:io-add-key-event
   #:io-add-mouse-button-event
   #:io-add-mouse-pos-event
   #:io-add-mouse-source-event
   #:io-add-mouse-wheel-event
   #:io-clear-events-queue
   #:io-clear-input-keys
   #:io-clear-input-mouse
   #:io-set-app-accepting-events
   #:io-set-key-event-native-data
   #:io-set-key-event-native-data-ex
   #:is-any-item-active
   #:is-any-item-focused
   #:is-any-item-hovered
   #:is-any-mouse-down
   #:is-item-activated
   #:is-item-active
   #:is-item-clicked
   #:is-item-clicked-ex
   #:is-item-deactivated
   #:is-item-deactivated-after-edit
   #:is-item-edited
   #:is-item-focused
   #:is-item-hovered
   #:is-item-toggled-open
   #:is-item-toggled-selection
   #:is-item-visible
   #:is-key-chord-pressed
   #:is-key-down
   #:is-key-pressed
   #:is-key-pressed-ex
   #:is-key-released
   #:is-mouse-clicked
   #:is-mouse-clicked-ex
   #:is-mouse-double-clicked
   #:is-mouse-down
   #:is-mouse-dragging
   #:is-mouse-hovering-rect
   #:is-mouse-hovering-rect-ex
   #:is-mouse-pos-valid
   #:is-mouse-released
   #:is-mouse-released-with-delay
   #:is-popup-open
   #:is-rect-visible
   #:is-rect-visible-by-size
   #:is-window-appearing
   #:is-window-collapsed
   #:is-window-focused
   #:is-window-hovered
   #:item-flags
   #:item-flags-allow-duplicate-id
   #:item-flags-auto-close-popups
   #:item-flags-button-repeat
   #:item-flags-no-nav
   #:item-flags-no-nav-default-focus
   #:item-flags-no-tab-stop
   #:item-flags-none
   #:key
   #:key-0
   #:key-1
   #:key-2
   #:key-3
   #:key-4
   #:key-5
   #:key-6
   #:key-7
   #:key-8
   #:key-9
   #:key-a
   #:key-apostrophe
   #:key-app-back
   #:key-app-forward
   #:key-b
   #:key-backslash
   #:key-backspace
   #:key-c
   #:key-caps-lock
   #:key-chord
   #:key-comma
   #:key-count
   #:key-d
   #:key-data
   #:key-delete
   #:key-down-arrow
   #:key-e
   #:key-end
   #:key-enter
   #:key-equal
   #:key-escape
   #:key-f
   #:key-f1
   #:key-f10
   #:key-f11
   #:key-f12
   #:key-f13
   #:key-f14
   #:key-f15
   #:key-f16
   #:key-f17
   #:key-f18
   #:key-f19
   #:key-f2
   #:key-f20
   #:key-f21
   #:key-f22
   #:key-f23
   #:key-f24
   #:key-f3
   #:key-f4
   #:key-f5
   #:key-f6
   #:key-f7
   #:key-f8
   #:key-f9
   #:key-g
   #:key-gamepad-back
   #:key-gamepad-dpad-down
   #:key-gamepad-dpad-left
   #:key-gamepad-dpad-right
   #:key-gamepad-dpad-up
   #:key-gamepad-face-down
   #:key-gamepad-face-left
   #:key-gamepad-face-right
   #:key-gamepad-face-up
   #:key-gamepad-l1
   #:key-gamepad-l2
   #:key-gamepad-l3
   #:key-gamepad-lstick-down
   #:key-gamepad-lstick-left
   #:key-gamepad-lstick-right
   #:key-gamepad-lstick-up
   #:key-gamepad-r1
   #:key-gamepad-r2
   #:key-gamepad-r3
   #:key-gamepad-rstick-down
   #:key-gamepad-rstick-left
   #:key-gamepad-rstick-right
   #:key-gamepad-rstick-up
   #:key-gamepad-start
   #:key-grave-accent
   #:key-h
   #:key-home
   #:key-i
   #:key-insert
   #:key-j
   #:key-k
   #:key-keypad-add
   #:key-keypad-decimal
   #:key-keypad-divide
   #:key-keypad-enter
   #:key-keypad-equal
   #:key-keypad-multiply
   #:key-keypad-subtract
   #:key-keypad0
   #:key-keypad1
   #:key-keypad2
   #:key-keypad3
   #:key-keypad4
   #:key-keypad5
   #:key-keypad6
   #:key-keypad7
   #:key-keypad8
   #:key-keypad9
   #:key-l
   #:key-left-alt
   #:key-left-arrow
   #:key-left-bracket
   #:key-left-ctrl
   #:key-left-shift
   #:key-left-super
   #:key-m
   #:key-menu
   #:key-minus
   #:key-mouse-left
   #:key-mouse-middle
   #:key-mouse-right
   #:key-mouse-wheel-x
   #:key-mouse-wheel-y
   #:key-mouse-x1
   #:key-mouse-x2
   #:key-n
   #:key-named-key-begin
   #:key-named-key-count
   #:key-named-key-end
   #:key-none
   #:key-num-lock
   #:key-o
   #:key-oem102
   #:key-p
   #:key-page-down
   #:key-page-up
   #:key-pause
   #:key-period
   #:key-print-screen
   #:key-q
   #:key-r
   #:key-reserved-for-mod-alt
   #:key-reserved-for-mod-ctrl
   #:key-reserved-for-mod-shift
   #:key-reserved-for-mod-super
   #:key-right-alt
   #:key-right-arrow
   #:key-right-bracket
   #:key-right-ctrl
   #:key-right-shift
   #:key-right-super
   #:key-s
   #:key-scroll-lock
   #:key-semicolon
   #:key-slash
   #:key-space
   #:key-t
   #:key-tab
   #:key-u
   #:key-up-arrow
   #:key-v
   #:key-w
   #:key-x
   #:key-y
   #:key-z
   #:label-text
   #:label-text-v
   #:list-box
   #:list-box-callback
   #:list-box-callback-ex
   #:list-box-obsolete
   #:list-box-obsolete-ex
   #:list-clipper
   #:list-clipper-begin
   #:list-clipper-end
   #:list-clipper-flags
   #:list-clipper-flags-no-set-table-row-counters
   #:list-clipper-flags-none
   #:list-clipper-include-item-by-index
   #:list-clipper-include-items-by-index
   #:list-clipper-seek-cursor-for-item
   #:list-clipper-step
   #:load-ini-settings-from-disk
   #:load-ini-settings-from-memory
   #:log-buttons
   #:log-finish
   #:log-text
   #:log-text-v
   #:log-to-clipboard
   #:log-to-file
   #:log-to-tty
   #:mem-alloc
   #:mem-alloc-func
   #:mem-free
   #:mem-free-func
   #:menu-item
   #:menu-item-bool-ptr
   #:menu-item-ex
   #:mod-alt
   #:mod-ctrl
   #:mod-mask-
   #:mod-none
   #:mod-shift
   #:mod-shortcut
   #:mod-super
   #:mouse-button
   #:mouse-button-count
   #:mouse-button-left
   #:mouse-button-middle
   #:mouse-button-right
   #:mouse-cursor
   #:mouse-cursor-arrow
   #:mouse-cursor-count
   #:mouse-cursor-hand
   #:mouse-cursor-none
   #:mouse-cursor-not-allowed
   #:mouse-cursor-progress
   #:mouse-cursor-resize-all
   #:mouse-cursor-resize-ew
   #:mouse-cursor-resize-nesw
   #:mouse-cursor-resize-ns
   #:mouse-cursor-resize-nwse
   #:mouse-cursor-text-input
   #:mouse-cursor-wait
   #:mouse-source
   #:mouse-source-count
   #:mouse-source-mouse
   #:mouse-source-pen
   #:mouse-source-touch-screen
   #:multi-select-flags
   #:multi-select-flags-box-select-no-scroll
   #:multi-select-flags-box-select1d
   #:multi-select-flags-box-select2d
   #:multi-select-flags-clear-on-click-void
   #:multi-select-flags-clear-on-escape
   #:multi-select-flags-nav-wrap-x
   #:multi-select-flags-no-auto-clear
   #:multi-select-flags-no-auto-clear-on-reselect
   #:multi-select-flags-no-auto-select
   #:multi-select-flags-no-range-select
   #:multi-select-flags-no-select-all
   #:multi-select-flags-no-select-on-right-click
   #:multi-select-flags-none
   #:multi-select-flags-scope-rect
   #:multi-select-flags-scope-window
   #:multi-select-flags-select-on-click
   #:multi-select-flags-select-on-click-release
   #:multi-select-flags-single-select
   #:multi-select-io
   #:new-frame
   #:new-line
   #:next-column
   #:open-popup
   #:open-popup-id
   #:open-popup-on-item-click
   #:payload
   #:payload-clear
   #:payload-is-data-type
   #:payload-is-delivery
   #:payload-is-preview
   #:platform-ime-data
   #:platform-io
   #:platform-io-clear-platform-handlers
   #:platform-io-clear-renderer-handlers
   #:plot-histogram
   #:plot-histogram-callback
   #:plot-histogram-callback-ex
   #:plot-histogram-ex
   #:plot-lines
   #:plot-lines-callback
   #:plot-lines-callback-ex
   #:plot-lines-ex
   #:pop-button-repeat
   #:pop-clip-rect
   #:pop-font
   #:pop-id
   #:pop-item-flag
   #:pop-item-width
   #:pop-style-color
   #:pop-style-color-ex
   #:pop-style-var
   #:pop-style-var-ex
   #:pop-tab-stop
   #:pop-text-wrap-pos
   #:popup-flags
   #:popup-flags-any-popup
   #:popup-flags-any-popup-id
   #:popup-flags-any-popup-level
   #:popup-flags-mouse-button-default-
   #:popup-flags-mouse-button-left
   #:popup-flags-mouse-button-mask-
   #:popup-flags-mouse-button-middle
   #:popup-flags-mouse-button-right
   #:popup-flags-no-open-over-existing-popup
   #:popup-flags-no-open-over-items
   #:popup-flags-no-reopen
   #:popup-flags-none
   #:progress-bar
   #:push-button-repeat
   #:push-clip-rect
   #:push-font
   #:push-font-float
   #:push-id
   #:push-idint
   #:push-idptr
   #:push-idstr
   #:push-item-flag
   #:push-item-width
   #:push-style-color
   #:push-style-color-im-vec4
   #:push-style-var
   #:push-style-var-im-vec2
   #:push-style-var-x
   #:push-style-var-y
   #:push-tab-stop
   #:push-text-wrap-pos
   #:radio-button
   #:radio-button-int-ptr
   #:render
   #:reset-mouse-drag-delta
   #:reset-mouse-drag-delta-ex
   #:s16
   #:s32
   #:s64
   #:s8
   #:same-line
   #:same-line-ex
   #:save-ini-settings-to-disk
   #:save-ini-settings-to-memory
   #:selectable
   #:selectable-bool-ptr
   #:selectable-bool-ptr-ex
   #:selectable-ex
   #:selectable-flags
   #:selectable-flags-allow-double-click
   #:selectable-flags-allow-overlap
   #:selectable-flags-disabled
   #:selectable-flags-dont-close-popups
   #:selectable-flags-highlight
   #:selectable-flags-no-auto-close-popups
   #:selectable-flags-none
   #:selectable-flags-select-on-nav
   #:selectable-flags-span-all-columns
   #:selection-basic-storage
   #:selection-basic-storage-apply-requests
   #:selection-basic-storage-clear
   #:selection-basic-storage-contains
   #:selection-basic-storage-get-next-selected-item
   #:selection-basic-storage-get-storage-id-from-index
   #:selection-basic-storage-set-item-selected
   #:selection-basic-storage-swap
   #:selection-external-storage
   #:selection-external-storage-apply-requests
   #:selection-request
   #:selection-request-type-none
   #:selection-request-type-set-all
   #:selection-request-type-set-range
   #:selection-user-data
   #:separator
   #:separator-text
   #:set-allocator-functions
   #:set-clipboard-text
   #:set-color-edit-options
   #:set-column-offset
   #:set-column-width
   #:set-current-context
   #:set-cursor-pos
   #:set-cursor-pos-x
   #:set-cursor-pos-y
   #:set-cursor-screen-pos
   #:set-drag-drop-payload
   #:set-item-default-focus
   #:set-item-key-owner
   #:set-item-tooltip
   #:set-item-tooltip-v
   #:set-keyboard-focus-here
   #:set-keyboard-focus-here-ex
   #:set-mouse-cursor
   #:set-nav-cursor-visible
   #:set-next-frame-want-capture-keyboard
   #:set-next-frame-want-capture-mouse
   #:set-next-item-allow-overlap
   #:set-next-item-open
   #:set-next-item-selection-user-data
   #:set-next-item-shortcut
   #:set-next-item-storage-id
   #:set-next-item-width
   #:set-next-window-bg-alpha
   #:set-next-window-collapsed
   #:set-next-window-content-size
   #:set-next-window-focus
   #:set-next-window-pos
   #:set-next-window-pos-ex
   #:set-next-window-scroll
   #:set-next-window-size
   #:set-next-window-size-constraints
   #:set-scroll-from-pos-x
   #:set-scroll-from-pos-y
   #:set-scroll-here-x
   #:set-scroll-here-y
   #:set-scroll-x
   #:set-scroll-y
   #:set-state-storage
   #:set-tab-item-closed
   #:set-tooltip
   #:set-tooltip-v
   #:set-window-collapsed
   #:set-window-collapsed-str
   #:set-window-focus
   #:set-window-focus-str
   #:set-window-font-scale
   #:set-window-pos
   #:set-window-pos-str
   #:set-window-size
   #:set-window-size-str
   #:shortcut
   #:show-about-window
   #:show-debug-log-window
   #:show-demo-window
   #:show-font-selector
   #:show-idstack-tool-window
   #:show-idstack-tool-window-ex
   #:show-metrics-window
   #:show-stack-tool-window
   #:show-style-editor
   #:show-style-selector
   #:show-user-guide
   #:size-callback
   #:size-callback-data
   #:slider-angle
   #:slider-angle-ex
   #:slider-flags
   #:slider-flags-always-clamp
   #:slider-flags-clamp-on-input
   #:slider-flags-clamp-zero-range
   #:slider-flags-color-markers
   #:slider-flags-invalid-mask-
   #:slider-flags-logarithmic
   #:slider-flags-no-input
   #:slider-flags-no-round-to-format
   #:slider-flags-no-speed-tweaks
   #:slider-flags-none
   #:slider-flags-wrap-around
   #:slider-float
   #:slider-float-ex
   #:slider-float2
   #:slider-float2ex
   #:slider-float3
   #:slider-float3ex
   #:slider-float4
   #:slider-float4ex
   #:slider-int
   #:slider-int-ex
   #:slider-int2
   #:slider-int2ex
   #:slider-int3
   #:slider-int3ex
   #:slider-int4
   #:slider-int4ex
   #:slider-scalar
   #:slider-scalar-ex
   #:slider-scalar-n
   #:slider-scalar-nex
   #:small-button
   #:sort-direction
   #:sort-direction-ascending
   #:sort-direction-descending
   #:sort-direction-none
   #:spacing
   #:storage
   #:storage-build-sort-by-key
   #:storage-clear
   #:storage-get-bool
   #:storage-get-bool-ref
   #:storage-get-float
   #:storage-get-float-ref
   #:storage-get-int
   #:storage-get-int-ref
   #:storage-get-void-ptr
   #:storage-get-void-ptr-ref
   #:storage-pair
   #:storage-set-all-int
   #:storage-set-bool
   #:storage-set-float
   #:storage-set-int
   #:storage-set-void-ptr
   #:str-from-char-str
   #:style
   #:style-colors-classic
   #:style-colors-dark
   #:style-colors-light
   #:style-scale-all-sizes
   #:style-var
   #:style-var-alpha
   #:style-var-button-text-align
   #:style-var-cell-padding
   #:style-var-child-border-size
   #:style-var-child-rounding
   #:style-var-count
   #:style-var-disabled-alpha
   #:style-var-frame-border-size
   #:style-var-frame-padding
   #:style-var-frame-rounding
   #:style-var-grab-min-size
   #:style-var-grab-rounding
   #:style-var-image-border-size
   #:style-var-indent-spacing
   #:style-var-item-inner-spacing
   #:style-var-item-spacing
   #:style-var-popup-border-size
   #:style-var-popup-rounding
   #:style-var-scrollbar-padding
   #:style-var-scrollbar-rounding
   #:style-var-scrollbar-size
   #:style-var-selectable-text-align
   #:style-var-separator-text-align
   #:style-var-separator-text-border-size
   #:style-var-separator-text-padding
   #:style-var-tab-bar-border-size
   #:style-var-tab-bar-overline-size
   #:style-var-tab-border-size
   #:style-var-tab-min-width-base
   #:style-var-tab-min-width-shrink
   #:style-var-tab-rounding
   #:style-var-table-angled-headers-angle
   #:style-var-table-angled-headers-text-align
   #:style-var-tree-lines-rounding
   #:style-var-tree-lines-size
   #:style-var-window-border-size
   #:style-var-window-min-size
   #:style-var-window-padding
   #:style-var-window-rounding
   #:style-var-window-title-align
   #:tab-bar-flags
   #:tab-bar-flags-auto-select-new-tabs
   #:tab-bar-flags-draw-selected-overline
   #:tab-bar-flags-fitting-policy-default-
   #:tab-bar-flags-fitting-policy-mask-
   #:tab-bar-flags-fitting-policy-mixed
   #:tab-bar-flags-fitting-policy-resize-down
   #:tab-bar-flags-fitting-policy-scroll
   #:tab-bar-flags-fitting-policy-shrink
   #:tab-bar-flags-no-close-with-middle-mouse-button
   #:tab-bar-flags-no-tab-list-scrolling-buttons
   #:tab-bar-flags-no-tooltip
   #:tab-bar-flags-none
   #:tab-bar-flags-reorderable
   #:tab-bar-flags-tab-list-popup-button
   #:tab-item-button
   #:tab-item-flags
   #:tab-item-flags-leading
   #:tab-item-flags-no-assumed-closure
   #:tab-item-flags-no-close-with-middle-mouse-button
   #:tab-item-flags-no-push-id
   #:tab-item-flags-no-reorder
   #:tab-item-flags-no-tooltip
   #:tab-item-flags-none
   #:tab-item-flags-set-selected
   #:tab-item-flags-trailing
   #:tab-item-flags-unsaved-document
   #:table-angled-headers-row
   #:table-bg-target
   #:table-bg-target-cell-bg
   #:table-bg-target-none
   #:table-bg-target-row-bg0
   #:table-bg-target-row-bg1
   #:table-column-flags
   #:table-column-flags-angled-header
   #:table-column-flags-default-hide
   #:table-column-flags-default-sort
   #:table-column-flags-disabled
   #:table-column-flags-indent-disable
   #:table-column-flags-indent-enable
   #:table-column-flags-indent-mask-
   #:table-column-flags-is-enabled
   #:table-column-flags-is-hovered
   #:table-column-flags-is-sorted
   #:table-column-flags-is-visible
   #:table-column-flags-no-clip
   #:table-column-flags-no-direct-resize-
   #:table-column-flags-no-header-label
   #:table-column-flags-no-header-width
   #:table-column-flags-no-hide
   #:table-column-flags-no-reorder
   #:table-column-flags-no-resize
   #:table-column-flags-no-sort
   #:table-column-flags-no-sort-ascending
   #:table-column-flags-no-sort-descending
   #:table-column-flags-none
   #:table-column-flags-prefer-sort-ascending
   #:table-column-flags-prefer-sort-descending
   #:table-column-flags-status-mask-
   #:table-column-flags-width-fixed
   #:table-column-flags-width-mask-
   #:table-column-flags-width-stretch
   #:table-column-sort-specs
   #:table-flags
   #:table-flags-borders
   #:table-flags-borders-h
   #:table-flags-borders-inner
   #:table-flags-borders-inner-h
   #:table-flags-borders-inner-v
   #:table-flags-borders-outer
   #:table-flags-borders-outer-h
   #:table-flags-borders-outer-v
   #:table-flags-borders-v
   #:table-flags-context-menu-in-body
   #:table-flags-hideable
   #:table-flags-highlight-hovered-column
   #:table-flags-no-borders-in-body
   #:table-flags-no-borders-in-body-until-resize
   #:table-flags-no-clip
   #:table-flags-no-host-extend-x
   #:table-flags-no-host-extend-y
   #:table-flags-no-keep-columns-visible
   #:table-flags-no-pad-inner-x
   #:table-flags-no-pad-outer-x
   #:table-flags-no-saved-settings
   #:table-flags-none
   #:table-flags-pad-outer-x
   #:table-flags-precise-widths
   #:table-flags-reorderable
   #:table-flags-resizable
   #:table-flags-row-bg
   #:table-flags-scroll-x
   #:table-flags-scroll-y
   #:table-flags-sizing-fixed-fit
   #:table-flags-sizing-fixed-same
   #:table-flags-sizing-mask-
   #:table-flags-sizing-stretch-prop
   #:table-flags-sizing-stretch-same
   #:table-flags-sort-multi
   #:table-flags-sort-tristate
   #:table-flags-sortable
   #:table-get-column-count
   #:table-get-column-flags
   #:table-get-column-index
   #:table-get-column-name
   #:table-get-hovered-column
   #:table-get-row-index
   #:table-get-sort-specs
   #:table-header
   #:table-headers-row
   #:table-next-column
   #:table-next-row
   #:table-next-row-ex
   #:table-row-flags
   #:table-row-flags-headers
   #:table-row-flags-none
   #:table-set-bg-color
   #:table-set-column-enabled
   #:table-set-column-index
   #:table-setup-column
   #:table-setup-column-ex
   #:table-setup-scroll-freeze
   #:table-sort-specs
   #:text
   #:text-buffer
   #:text-buffer-append
   #:text-buffer-appendf
   #:text-buffer-appendfv
   #:text-buffer-begin
   #:text-buffer-c-str
   #:text-buffer-clear
   #:text-buffer-empty
   #:text-buffer-end
   #:text-buffer-reserve
   #:text-buffer-resize
   #:text-buffer-size
   #:text-colored
   #:text-colored-v
   #:text-disabled
   #:text-disabled-v
   #:text-filter
   #:text-filter-build
   #:text-filter-clear
   #:text-filter-draw
   #:text-filter-im-gui-text-range
   #:text-filter-im-gui-text-range-empty
   #:text-filter-im-gui-text-range-split
   #:text-filter-is-active
   #:text-filter-pass-filter
   #:text-link
   #:text-link-open-url
   #:text-link-open-urlex
   #:text-unformatted
   #:text-unformatted-ex
   #:text-v
   #:text-wrapped
   #:text-wrapped-v
   #:texture-data
   #:texture-data-create
   #:texture-data-destroy-pixels
   #:texture-data-get-pitch
   #:texture-data-get-pixels
   #:texture-data-get-pixels-at
   #:texture-data-get-size-in-bytes
   #:texture-data-get-tex-id
   #:texture-data-get-tex-ref
   #:texture-data-set-status
   #:texture-data-set-tex-id
   #:texture-format-alpha8
   #:texture-format-rgba32
   #:texture-id
   #:texture-rect
   #:texture-ref
   #:texture-ref-get-tex-id
   #:texture-status-destroyed
   #:texture-status-ok
   #:texture-status-want-create
   #:texture-status-want-destroy
   #:texture-status-want-updates
   #:tree-node
   #:tree-node-ex
   #:tree-node-ex-ptr
   #:tree-node-ex-str
   #:tree-node-ex-v
   #:tree-node-ex-vptr
   #:tree-node-flags
   #:tree-node-flags-allow-overlap
   #:tree-node-flags-bullet
   #:tree-node-flags-collapsing-header
   #:tree-node-flags-default-open
   #:tree-node-flags-draw-lines-full
   #:tree-node-flags-draw-lines-none
   #:tree-node-flags-draw-lines-to-nodes
   #:tree-node-flags-frame-padding
   #:tree-node-flags-framed
   #:tree-node-flags-label-span-all-columns
   #:tree-node-flags-leaf
   #:tree-node-flags-nav-left-jumps-back-here
   #:tree-node-flags-nav-left-jumps-to-parent
   #:tree-node-flags-no-auto-open-on-log
   #:tree-node-flags-no-tree-push-on-open
   #:tree-node-flags-none
   #:tree-node-flags-open-on-arrow
   #:tree-node-flags-open-on-double-click
   #:tree-node-flags-selected
   #:tree-node-flags-span-all-columns
   #:tree-node-flags-span-avail-width
   #:tree-node-flags-span-full-width
   #:tree-node-flags-span-label-width
   #:tree-node-flags-span-text-width
   #:tree-node-ptr
   #:tree-node-str
   #:tree-node-v
   #:tree-node-vptr
   #:tree-pop
   #:tree-push
   #:tree-push-ptr
   #:u16
   #:u32
   #:u64
   #:u8
   #:unindent
   #:unindent-ex
   #:vec2
   #:vec4
   #:vector-char
   #:vector-construct
   #:vector-destruct
   #:vector-float
   #:vector-im-draw-channel
   #:vector-im-draw-cmd
   #:vector-im-draw-idx
   #:vector-im-draw-list-ptr
   #:vector-im-draw-list-shared-data-ptr
   #:vector-im-draw-vert
   #:vector-im-font-config
   #:vector-im-font-config-ptr
   #:vector-im-font-glyph
   #:vector-im-font-ptr
   #:vector-im-gui-selection-request
   #:vector-im-gui-storage-pair
   #:vector-im-gui-text-range
   #:vector-im-texture-data-ptr
   #:vector-im-texture-rect
   #:vector-im-texture-ref
   #:vector-im-u16
   #:vector-im-u32
   #:vector-im-u8
   #:vector-im-vec2
   #:vector-im-vec4
   #:vector-im-wchar
   #:viewport
   #:viewport-flags
   #:viewport-flags-is-platform-monitor
   #:viewport-flags-is-platform-window
   #:viewport-flags-none
   #:viewport-flags-owned-by-app
   #:viewport-get-center
   #:viewport-get-work-center
   #:vslider-float
   #:vslider-float-ex
   #:vslider-int
   #:vslider-int-ex
   #:vslider-scalar
   #:vslider-scalar-ex
   #:wchar
   #:wchar16
   #:wchar32
   #:window-flags
   #:window-flags-always-auto-resize
   #:window-flags-always-horizontal-scrollbar
   #:window-flags-always-vertical-scrollbar
   #:window-flags-child-menu
   #:window-flags-child-window
   #:window-flags-horizontal-scrollbar
   #:window-flags-menu-bar
   #:window-flags-modal
   #:window-flags-no-background
   #:window-flags-no-bring-to-front-on-focus
   #:window-flags-no-collapse
   #:window-flags-no-decoration
   #:window-flags-no-focus-on-appearing
   #:window-flags-no-inputs
   #:window-flags-no-mouse-inputs
   #:window-flags-no-move
   #:window-flags-no-nav
   #:window-flags-no-nav-focus
   #:window-flags-no-nav-inputs
   #:window-flags-no-resize
   #:window-flags-no-saved-settings
   #:window-flags-no-scroll-with-mouse
   #:window-flags-no-scrollbar
   #:window-flags-no-title-bar
   #:window-flags-none
   #:window-flags-popup
   #:window-flags-tooltip
   #:window-flags-unsaved-document
   ))
